# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: portfolio-api
#   namespace: k9s
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: k9s
#   template:
#     metadata:
#       labels:
#         app: k9s
#     spec:
#       serviceAccountName: k9s-sa
#       initContainers:
#         - name: kubeconfig-writer
#           image: busybox:1.36
#           command: ["/bin/sh", "-c"]
#           args:
#             - /mnt/script/write-kubeconfig.sh chmod 644 /kube/config
#           volumeMounts:
#             - name: scripts
#               mountPath: /mnt/script
#             - name: kubeconfig
#               mountPath: /kube
#       containers:
#         - name: portfolio-k9s
#           image: derailed/k9s:latest
#           command: ["/bin/sh"]
#           # command: ["/bin/sh", "-c"]
#           tty: true
#           stdin: true
#           # args:
#           #   # Install ncurses, switch to k9s user, then run k9s in headless readonly mode showing all namespaces
#           #   - apk add ncurses && sh
#           env:
#             - name: KUBECONFIG
#               value: /kube/config
#           volumeMounts:
#             - name: kubeconfig
#               mountPath: /kube
#           # securityContext:
#           #   runAsUser: 1000
#           #   runAsGroup: 2000
#       volumes:
#         - name: scripts
#           configMap:
#             name: k9s-scripts
#             defaultMode: 0755
#         - name: kubeconfig
#           emptyDir: {}
