apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: ghcr.io/aidenharwood/portfolio/frontend:17930361883-55
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: "https://api.aidenharwood.uk"
          # - name: NODE_OPTIONS
          #   value: --require @opentelemetry/auto-instrumentations-node/register
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: http://lgtm-alloy.lgtm.svc.cluster.local:4318
