apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: ghcr.io/aidenharwood/portfolio/frontend:16756636486-20
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: "http://portfolio-api:80"
