apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
        - name: portfolio-frontend
          image: ghcr.io/aidenharwood/portfolio/api:16756930127-3
          ports:
            - containerPort: 3000
