apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
        - name: portfolio-frontend
          image: ghcr.io/aidenharwood/portfolio/api:16757693522-6
          ports:
            - containerPort: 4000
          volumeMounts:
          - mountPath: /app/blog
            name: blog
            readOnly: true
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.4.2
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/aidenharwood/portfolio-markdown-blog.git"
            - name: GITSYNC_ROOT
              value: "/git"
            - name: GITSYNC_DEST
              value: "/mnt/git"
            - name: GITSYNC_ONE_TIME
              value: "false"
            - name: GITSYNC_PERIOD
              value: "60m"
          volumeMounts:
          - mountPath: /mnt/git
            name: blog
      volumes:
      - name: blog
        emptyDir:
          sizeLimit: 500Mi
