apiVersion: v1
kind: ConfigMap
metadata:
  name: api-scripts
data:
{{- $files := .Files.Glob "_scripts/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
    {{ $file | indent 4 }}
{{- end }}