apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-api-exec
  namespace: website
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create
      - get