apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-api-exec
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods/exec
      - pods/attach
      - pods/portforward
    verbs:
      - create
      - get