apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-api-sa-role
  namespace: portfolio-api
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/attach
      - pods/portforward
    verbs:
      - create
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-api-sa-rolebinding
  namespace: portfolio-api
subjects:
  - kind: ServiceAccount
    name: portfolio-api-sa
roleRef:
  kind: Role
  name: portfolio-api-sa-role
  apiGroup: rbac.authorization.k8s.io