apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-api-sa-role
  namespace: k9s
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create
      - get
  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-api-sa-rolebinding
  namespace: k9s
subjects:
  - kind: ServiceAccount
    name: portfolio-api-sa
    namespace: website
roleRef:
  kind: Role
  name: portfolio-api-sa-role
  apiGroup: rbac.authorization.k8s.io